#!/bin/bash

live-localepurge(){

# Based on http://git.overlays.gentoo.org/gitweb/?p=proj/localepurge.git;a=summary
# да-да "ненужно" :3
# Deleting all locale files on system
# *not* listed in ${LINGUAS}

set -e

VERSION="0.2"

for lang in ${LINGUAS};do
	if [[ ${lang} != *_* ]];then
		UP=$(tr [a-z] [A-Z] <<< "${lang}")
		LINGUAS+=" ${lang}_${UP}"
	fi
done

LOCALETOTAL=0
MANTOTAL=0
SPACETMP=0

GOOD=$'\e[32;01m'
NORMAL=$'\e[0m'
BOLD=$'\e[1m'

ACTION="rm -vf"
DIR_ACTION="rm -vfr"

info () { echo -e " ${GOOD}*${NORMAL} $*";}

# Deleting a filepath and optionally counting freed space
remove() {
	local REMOVEPATH="$1"
	SPACEBEFORE=$(df -P ${REMOVEPATH}| awk '{if ( NR==2 ) { print $3 }}')
	${ACTION} `find ${REMOVEPATH} -type f -o -type l`
	[ -z "$(find ${REMOVEPATH} -type f -o -type l)" ] && ${DIR_ACTION} ${REMOVEPATH}
	# if symlink, REMOVEPATH could be removed
	# check from parentdir then
	if [ -d ${REMOVEPATH} ]; then
		SPACEAFTER=$(df -P ${REMOVEPATH} | awk '{if ( NR==2 ) { print $3 }}')
	else
		SPACEAFTER=$(df -P ${REMOVEPATH%/*} | awk '{if ( NR==2 ) { print $3 }}')
	fi
	SPACESUM=$(($SPACEBEFORE - $SPACEAFTER))
	if test $SPACESUM -gt 0 ; then
		SPACETMP=$(($SPACETMP + $SPACESUM))
	fi
}

# Getting rid of superfluous locale files in $LOCALEDIR:
purgelocale () {
	local ALL_DIRS="$(find ${D} -type d -name LC_MESSAGES)"
	if [ -n "${ALL_DIRS}" ];then
		for lang in ${LINGUAS};do
			local GOOD_LOCALES+="/${lang}/LC_MESSAGES\n"
		done
		GOOD_LOCALES="$(echo -e "${GOOD_LOCALES}")"
		local TRASHLIST="$(grep -v "${GOOD_LOCALES}" <<< "${ALL_DIRS}")"
		for DIR in ${TRASHLIST};do
			remove "${DIR%/LC_MESSAGES}"
		done
		if test $SPACETMP -gt 0 ; then
			LOCALETOTAL=$(($LOCALETOTAL + $SPACETMP))
			info "live-localepurge: Disk space freed in $LOCALEDIR: ${BOLD}"$SPACETMP"K${NORMAL}"
		fi
		SPACETMP=0
	fi
}

purgeman(){
	local MAN_DIRS="$(find ${D} -type d -name 'man')"
	for lang in ${LINGUAS};do
		local GOOD_MAN+="/man/${lang}\n"
	done
	GOOD_MAN="$(echo -e "${GOOD_MAN}")"
	if [ -n "${MAN_DIRS}" ];then
		for DIR in ${MAN_DIRS};do
			local SUBDIRS="$(ls -d1 ${DIR}/* | grep -v "/man[1-9]")"
		done

		local TRASHLIST="$(grep -v "${GOOD_MAN}" <<< "${SUBDIRS}")"
		for DIR in ${TRASHLIST};do
			remove "${DIR}"
		done
		if test $SPACETMP -gt 0 ; then
			MANTOTAL=$(($MANTOTAL + $SPACETMP))
			info "live-localepurge: Disk space freed in $MANPAGEDIR: ${BOLD}"$SPACETMP"K${NORMAL}"
		fi
		SPACETMP=0
	fi
}

purgelocale

purgeman

# Calculating and reporting total disk space freed:
TOTAL=$(($LOCALETOTAL+$MANTOTAL))
test $TOTAL -lt 0 && TOTAL=0
if [[ "${TOTAL}" != "0" ]];then
	elog "Total disk space freed by live-localepurge: ${BOLD}"$TOTAL"K${NORMAL}"
fi
}

post_src_install(){ live-localepurge;}
