#!/bin/bash

restore="\033[00m"
underline="\033[4m"

[[ -h "/etc/make.profile" ]] && makeprof="/etc/make.profile"
[[ -h "/etc/portage/make.profile" ]] && makeprof="/etc/portage/make.profile"

profile() {
	file="${1}/package.use.mask"
	if [[ -f "${file}" ]];then
		output="$(grep -20 "^[^#].*${2}" "${file}" | sed -ne "/^#.*${2}/d" -e '/./{H;$!d;}' -ne "x;/${2}/p;")"
		[[ -n "${output}" ]] && echo -e $'\n'"${underline}${file}${restore}:"$'\n'"${output}"
	fi
	if [[ -f "${1}/parent" ]]; then
		for path in $(cat ${1}/parent);do
			profile "${1}/${path}" "${2}"
		done
	fi
}

profile "$(readlink ${makeprof} | sed -e 's|\.\.||')" "${1}"
